# dir.create('~/data/')
# dir.create('~/data/2021/')
# dir.create('~/data/1920/')
# dir.create('~/data/1819/')
# dir.create('~/data/1718/')
# dir.create('~/data/1617/')
dir.create('~/data/1516/')
dir.create('~/data/1415/')
base_dload_path <- 'https://www.football-data.co.uk/mmz4281/'
utils::download.file(file.path(base_dload_path, '2021', 'E0.csv'), file.path('~/data/', '2021', 'E0.csv'))
utils::download.file(file.path(base_dload_path, '1920', 'E0.csv'), file.path('~/data/', '1920', 'E0.csv'))
utils::download.file(file.path(base_dload_path, '1819', 'E0.csv'), file.path('~/data/', '1819', 'E0.csv'))
utils::download.file(file.path(base_dload_path, '1718', 'E0.csv'), file.path('~/data/', '1718', 'E0.csv'))
utils::download.file(file.path(base_dload_path, '1617', 'E0.csv'), file.path('~/data/', '1617', 'E0.csv'))
utils::download.file(file.path(base_dload_path, '1516', 'E0.csv'), file.path('~/data/', '1516', 'E0.csv'))
utils::download.file(file.path(base_dload_path, '1415', 'E0.csv'), file.path('~/data/', '1415', 'E0.csv'))

